### ISSUE TITLE
تغییر عنوان تبدیل معکوس

### ISSUE THREAD

**Issue by zoghal** [ganjoor/abjad#1]
سلام
داشتم محاسبه‌گر ابجد رو تست می‌کردم که برای اولین بار معکوس ابجد از این طریق آشنا شدم.
میدانید که ۱۱۰ ابجد علی است. حال اگر تست کنید معکوسش را بدرستی محاسبه نمی‌کند.
گفتم این مورد را جهت اطلاع گزارش کنم.
در ضمن از بابت تمامی زحماتی که برای سایت گنجور می‌کشید بنده به نوبه خودم ازتون صمیمانه تقدیر و تشکر میکنم.
خدا قوت

**Comment by hrmoh** [comment]
سلام
اگر مطلبی که در توضیح این تبدیل آمده مطالعه بفرمایید:
[تبدیل معکوس (عدد به حروف) ابجد](http://blog.ganjoor.net/1399/04/20/rev-abjad/)
متوجه می‌شوید که این تبدیل، معکوس ابجد نیست یعنی قرار نیست اعداد را بدهید و ابجد تحویل بگیرید.
اشکال اینجا عنوانی است که من برای این تبدیل انتخاب کرده‌ام. عنوان تبدیل معکوس عنوان مناسبی نیست. دوستانی که روش کار را توضیح داده‌اند (مطلب را ببینید) عنوانی برای این عملیات ارائه نداده‌اند.

به عنوان اشکال باز می‌توان تصحیح این عنوان را در دستور کار قرار داد.

**Comment by zoghal** [comment]
درود مجدد
بله بعد از این ایشو تازه متوجه قضیه شدم.
فقط ببخشید که نرسیدم زیاد به گیت سر بزنم :)
