### ISSUE TITLE
سازگاری با دستگاه‌های موبایل

### ISSUE THREAD

**Issue by hrmoh** [ganjoor/abjad#11]
روی دستگاه‌های موبایل عرض صفحه و کنترلها متناسب با عرض دستگاه تغییر نمی‌کند.

**Comment by hrmoh** [comment]
برای مشارکت پروژه را
fork
کنید و پس از اعمال تغییرات
pull request
بفرستید.

**Comment by ehsanghaffarii** [comment]
سلام، تغییرات رو انجام دادم.
یه فایل css اضافه کردم که استایل‌ها درونش باشن.
و مدیا کوئری بهش اضافه کردم که بشه هرچیزی رو باهاش ریسپانسیو کرد.

**Comment by hrmoh** [comment]
> سلام، تغییرات رو انجام دادم. یه فایل css اضافه کردم که استایل‌ها درونش باشن. و مدیا کوئری بهش اضافه کردم که بشه هرچیزی رو باهاش ریسپانسیو کرد.

سلام
من تغییرات را مرج کردم و الان روی سایت تغییرات شما هم وجود داره:
http://abjad.ganjoor.net/
منتهی علی رغم این که توی ریسپانسیو ویوی فایرفاکس تغییر دیده میشه روی کروم و روی کروم و فایرفاکس موبایل من تغییر رو نمی‌بینم. مشکل به نظر شما کجاست؟

**Comment by ehsanghaffarii** [comment]
بله چک کردم، تگ خیلی مهمی توی فایل `index.html` نبود. 
تگ viewport دقیقا مهمترین تک برای ریسپانسیو هستش.
تگ رو اضافه کردم و کامیت فرستادم.
با تشکر

**Comment by hrmoh** [comment]
> بله چک کردم، تگ خیلی مهمی توی فایل `index.html` نبود. تگ viewport دقیقا مهمترین تک برای ریسپانسیو هستش. تگ رو اضافه کردم و کامیت فرستادم. با تشکر

بسیار عالی!
الان پوشهٔ dist رو من پابلیش کردم و مسئله موقتا حل شده.
منتهی من پیشتر تلاش کردم و نتونستم بفهمم چطور میشه شبیه این مسئله رو اساسی حل کرد (من میخواستم تگ title به طور پیش فرض توی خروجی «محاسبه‌گر ابجد» باشه و نخوام خروجی رو دستی ویرایش کنم).
چطور میشه کاری کرد که این تغییرات با ساخت مجدد بیلد اتوماتیک توی خروجی ظاهر بشه که بعد از تغییرات بعدی با خیال راحت فقط بشه بیلد ساخت و خروجی رو پابلیش کرد.
میشه روی این تقاضا کنم وقت بذاری؟
ممنون

**Comment by ehsanghaffarii** [comment]
درسته.
در واقع توی یک پروژه‌ی نرمال همه‌ی المنت ها به صورت داینامیک لود میشه و کار میکنه.
در مورد این پروژه به خاطر اینکه دیدم سعی شده خیلی small باشه، سعی کردم چیزی بهش اضافه نکنم.
راه منطقی برای یک پروژه‌ نصب یک ماژول لود css یا sass هستش.  البته برای استایل دادن به اپ.
و برای مواردی مثل تغییر title و meta-tags به صورت داینامیک، داشتن یک router  هستش.

**Comment by ehsanghaffarii** [comment]
یه چیز خوب در مورد این پروژه اینه که کوچیکه و اضافه کردن ماژول‌ها و dependency ها مشکلی براش به وجود نمیاره.
می‌تونیم یه ساختار منطقی براش درست کنیم با نصب چندتا ماژول و نوشتن تعدادی کامپوننت.
این کار هم فضای بیشتری برای توسعه ایجاد میکنه و هم preformance رو بالا می بره.

**Comment by hrmoh** [comment]
این ایشو برای دوستانی که بتوانند آن را به گونه‌ای حل کنند که نیاز به دستکاری خروجیها نباشد هنوز باز است و حل شده محسوب نمی‌شود.

**Comment by ehsanghaffarii** [comment]
انجام شد

**Comment by hrmoh** [comment]
بسیار عالی
ممنون بابت این کار عالی
و همینطور بابت آیکونی که اضافه کردید.
